"""Transcode every demo source folder into web-friendly MP3 under
landing/audio/, and emit a single manifest.json the demo modules read
at runtime.

Two demos consume this output:

  Use case 01 — stem mixer (3 example tracks for DJ/producer/etc.)
    landing/audio/mixer/<song-id>/{drums,bass,other,vocals}.mp3

  Use case 02 — clean-vs-unclean A/B
    landing/audio/adaptive-combat/{drums,bass,other,vocals}.mp3
      (Demucs-separated from a full-mix Lyria generation)
    landing/audio/stems-isolated/{drums,bass,atmosphere}.mp3
      (each from its own isolation-focused Lyria prompt)
"""
from __future__ import annotations

import json
from pathlib import Path

from pydub import AudioSegment

ROOT = Path(__file__).resolve().parents[2]
OUTPUT_ROOT = ROOT / "output"
DST_ROOT = ROOT / "landing" / "audio"

MP3_BITRATE = "128k"

# ---- Use case 02 ----------------------------------------------------------
ADAPTIVE_SRC = OUTPUT_ROOT / "combat_library" / "combat_neutralbed_with_vocals__lyria"
ADAPTIVE_DST = DST_ROOT / "adaptive-combat"

ISOLATED_SOURCES = {
    "drums":      OUTPUT_ROOT / "combat_library" / "stem_test_drums_only__lyria"      / "drums.wav",
    "bass":       OUTPUT_ROOT / "combat_library" / "stem_test_bass_only__lyria"       / "bass.wav",
    "atmosphere": OUTPUT_ROOT / "combat_library" / "stem_test_atmosphere_only__lyria" / "other.wav",
}
ISOLATED_DST = DST_ROOT / "stems-isolated"

# Naive bass — generated by `landing/scripts/generate_naive_bass.py` from
# the prompt `"bass line, 130 BPM, E minor, electric bass"`. No isolation
# directives in the prompt, so Lyria fills the track with drums + groove
# even when you only asked for bass.
NAIVE_BASS_SRC = OUTPUT_ROOT / "naive_bass__lyria" / "generated_input.mp3"
NAIVE_BASS_DST = DST_ROOT / "naive" / "bass.mp3"

# Use case 03a — Bass A/B "raw vs. Demucs".
# A: the original Lyria mix from an isolation prompt. The model bleeds
#    drum hits into the bass track anyway — proves music models can't
#    fully isolate even when you tell them to.
# B: that same mix, after Demucs separation — clean bass alone.
# `bass.wav` is the pipeline's sliced loop (16 bars, ~29.5 s). The raw
# MP3 is the full untrimmed Lyria output. For an honest A/B we slice
# the raw to the same loop window before encoding so both files cover
# identical audio start-to-end.
BASS_AB_SRC_DIR   = OUTPUT_ROOT / "combat_library" / "stem_test_bass_only__lyria"
BASS_AB_SRC_RAW   = BASS_AB_SRC_DIR / "generated_input.mp3"
BASS_AB_SRC_CLEAN = BASS_AB_SRC_DIR / "bass.wav"
BASS_AB_SRC_CFG   = BASS_AB_SRC_DIR / "config.json"
BASS_AB_DST       = DST_ROOT / "bass-ab"

# Use case 03b — Prompt-engineering A/B, both after Demucs.
# Same Demucs step on both sides. Difference is the Lyria prompt
# that produced the source. Headline number: 43 dB cleaner
# bass-to-drums ratio when the prompt is engineered.
BASS_ENG_NAIVE_SRC = OUTPUT_ROOT / "stem_compare" / "naive_bass__lyria"      / "bass.wav"
BASS_ENG_ENG_SRC   = OUTPUT_ROOT / "stem_compare" / "engineered_bass__lyria" / "bass.wav"
BASS_ENG_DST       = DST_ROOT / "bass-engineering"

# ---- Use case 01 — three example tracks for the stem mixer ----------------
MIXER_DST = DST_ROOT / "mixer"

# Each entry: id used in URL + manifest, source folder, displayed metadata
MIXER_SONGS = [
    {
        "id":     "tech-house",
        "src":    OUTPUT_ROOT / "dj_inspiration" / "tech_house_124_v2__lyria",
        "label":  "Tech house · 124 BPM",
        "blurb":  "DJ inspiration — melodic hook",
        "scene":  "DJ",
    },
    {
        "id":     "lofi",
        "src":    OUTPUT_ROOT / "dj_inspiration" / "lofi_boom_bap_90__lyria",
        "label":  "Lo-fi boom-bap · 90 BPM",
        "blurb":  "DJ inspiration — jazzy rhodes",
        "scene":  "DJ",
    },
    {
        "id":     "synthpop",
        "src":    OUTPUT_ROOT / "producer_vocals" / "synthpop_female_110__lyria",
        "label":  "Synth pop · 110 BPM",
        "blurb":  "Producer — female lead vocal",
        "scene":  "Producer",
    },
]

STEMS = ("drums", "bass", "other", "vocals")


def transcode(src: Path, dst: Path) -> int:
    """Always re-encode through pydub so every file on the page has
    the same MP3 frame layout — Chrome's Web Audio decoder is fussy
    about MP3s from unknown encoders, even when other tools accept
    them. Handles both .wav and .mp3 input via `from_file`."""
    if dst.is_file() and dst.stat().st_mtime > src.stat().st_mtime:
        return dst.stat().st_size
    audio = AudioSegment.from_file(src)
    dst.parent.mkdir(parents=True, exist_ok=True)
    audio.export(dst, format="mp3", bitrate=MP3_BITRATE)
    return dst.stat().st_size


def build_adaptive_combat() -> tuple[dict, int]:
    print("Use case 02 — adaptive-combat (4 stems):")
    src_cfg = json.loads((ADAPTIVE_SRC / "config.json").read_text(encoding="utf-8"))
    ADAPTIVE_DST.mkdir(parents=True, exist_ok=True)
    total = 0
    for stem in STEMS:
        size = transcode(ADAPTIVE_SRC / f"{stem}.wav", ADAPTIVE_DST / f"{stem}.mp3")
        total += size
        print(f"  {stem:7} {size//1024:5d} KB")
    # `modes` are the Exploration/Combat preset gain values the game
    # demo crossfades between. They live in the source config.json
    # under "modes" — copy them through, fall back to canonical values
    # if the source doesn't carry them.
    modes = src_cfg.get("modes") or {
        "Exploration": {"drums": 0.0, "bass": 0.2, "other": 1.0, "vocals": 0.3},
        "Combat":      {"drums": 1.0, "bass": 1.0, "other": 0.7, "vocals": 0.5},
    }
    return ({
        "label": "Combat scene · neutral bed with vocals",
        "bpm": src_cfg.get("detected_bpm"),
        "bars": src_cfg.get("bars"),
        "loop_duration_ms": src_cfg.get("loop_duration_ms"),
        "modes": modes,
        "stems": [{"name": s, "file": f"{s}.mp3"} for s in STEMS],
        "base": "adaptive-combat",
    }, total)


def build_stems_isolated() -> tuple[dict, int]:
    print("Use case 02 — stems-isolated (3 stems):")
    ISOLATED_DST.mkdir(parents=True, exist_ok=True)
    total = 0
    for role, src in ISOLATED_SOURCES.items():
        size = transcode(src, ISOLATED_DST / f"{role}.mp3")
        total += size
        print(f"  {role:11} {size//1024:5d} KB")
    return ({
        "label": "Three stems · separately generated · 130 BPM · E minor",
        "bpm": 130,
        "key": "E minor",
        "stems": [
            {"name": "drums",      "file": "drums.mp3",
             "label": "Drums",      "isolation_db": 30,
             "blurb": "Drums at −17 dB, bass at −47 dB."},
            {"name": "bass",       "file": "bass.mp3",
             "label": "Bass",       "isolation_db": 17,
             "blurb": "Bass at −15 dB, drums at −32 dB."},
            {"name": "atmosphere", "file": "atmosphere.mp3",
             "label": "Atmosphere", "isolation_db": 54,
             "blurb": "Atmosphere at −17 dB, drums/bass at −71/−79 dB."},
        ],
        "base": "stems-isolated",
    }, total)


def build_mixer() -> tuple[dict, int]:
    print("Use case 01 — mixer (3 songs × 4 stems):")
    MIXER_DST.mkdir(parents=True, exist_ok=True)
    songs = []
    total = 0
    for spec in MIXER_SONGS:
        src = spec["src"]
        dst = MIXER_DST / spec["id"]
        dst.mkdir(parents=True, exist_ok=True)

        cfg_path = src / "config.json"
        cfg = json.loads(cfg_path.read_text(encoding="utf-8")) if cfg_path.is_file() else {}

        song_total = 0
        for stem in STEMS:
            size = transcode(src / f"{stem}.wav", dst / f"{stem}.mp3")
            song_total += size
        total += song_total
        print(f"  {spec['id']:10}  {song_total // 1024:5d} KB  ({spec['label']})")

        songs.append({
            "id": spec["id"],
            "label": spec["label"],
            "blurb": spec["blurb"],
            "scene": spec["scene"],
            "bpm": cfg.get("detected_bpm"),
            "bars": cfg.get("bars"),
            "loop_duration_ms": cfg.get("loop_duration_ms"),
            "base": f"mixer/{spec['id']}",
        })

    return ({
        "stems": [
            {"name": "drums",  "file": "drums.mp3",  "label": "Drums"},
            {"name": "bass",   "file": "bass.mp3",   "label": "Bass"},
            {"name": "other",  "file": "other.mp3",  "label": "Melody"},
            {"name": "vocals", "file": "vocals.mp3", "label": "Vocals"},
        ],
        "songs": songs,
        "default_song": songs[0]["id"] if songs else None,
    }, total)


def copy_mp3(src: Path, dst: Path) -> int:
    """Naive bass is already MP3 (Lyria returns MP3 natively). Just
    copy it into landing/audio/ — re-encoding would lose quality."""
    if dst.is_file() and dst.stat().st_mtime > src.stat().st_mtime:
        return dst.stat().st_size
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_bytes(src.read_bytes())
    return dst.stat().st_size


def build_bass_ab() -> tuple[dict, int]:
    """Use case 03a — two big A/B tiles for one instrument:
    raw isolation-prompt output vs. the same audio after Demucs.

    We slice the raw mix to the same loop window the pipeline used
    for bass.wav (from config.json) so the two tiles cover identical
    audio start-to-end and A↔B switches are sample-aligned. Without
    this slice, raw is the full untrimmed Lyria output while clean
    is the loop window → the two drift by the pre-loop offset.
    """
    print("Use case 03a — bass A/B (raw vs. Demucs):")
    BASS_AB_DST.mkdir(parents=True, exist_ok=True)

    cfg = json.loads(BASS_AB_SRC_CFG.read_text(encoding="utf-8"))
    start_ms = int(cfg["loop_start_ms"])
    end_ms   = int(cfg["loop_end_ms"])

    # Decode the raw Lyria MP3 to PCM, slice to [start_ms, end_ms],
    # then re-encode to MP3 through the same pydub pipeline bass.wav
    # uses. Result: both tiles are identical in length and aligned at
    # sample 0.
    raw_dst = BASS_AB_DST / "raw.mp3"
    raw_audio = AudioSegment.from_file(BASS_AB_SRC_RAW)[start_ms:end_ms]
    raw_dst.parent.mkdir(parents=True, exist_ok=True)
    raw_audio.export(raw_dst, format="mp3", bitrate=MP3_BITRATE)
    raw_size = raw_dst.stat().st_size
    print(f"  raw    {raw_size // 1024:5d} KB  "
          f"({(end_ms - start_ms) / 1000:.2f} s · sliced from full Lyria mix)")

    clean_size = transcode(BASS_AB_SRC_CLEAN, BASS_AB_DST / "clean.mp3")
    print(f"  clean  {clean_size // 1024:5d} KB  ({len(raw_audio) / 1000:.2f} s · Demucs bass)")
    total = raw_size + clean_size
    return ({
        "label": "Bass · isolation prompt",
        "prompt": "solo electric bass guitar recording, dry",
        "base": "bass-ab",
        "raw":   {"file": "raw.mp3",   "label": "Raw model output",
                  "blurb": "Even with an isolation prompt the model leaves drum hits in the mix."},
        "clean": {"file": "clean.mp3", "label": "After Demucs",
                  "blurb": "Same audio, separated. Clean bass alone."},
    }, total)


def build_bass_engineering() -> tuple[dict, int]:
    """Use case 03b — prompt-engineering A/B. Both inputs are already
    Demucs-separated bass stems; the only thing that differs is the
    Lyria prompt that produced the source mix. Measurements come from
    the parallel analysis run on these same files.
    """
    print("Use case 03b — bass A/B (naive vs engineered prompt, both Demucs):")
    BASS_ENG_DST.mkdir(parents=True, exist_ok=True)
    naive_size = transcode(BASS_ENG_NAIVE_SRC, BASS_ENG_DST / "naive.mp3")
    eng_size   = transcode(BASS_ENG_ENG_SRC,   BASS_ENG_DST / "engineered.mp3")
    print(f"  naive       {naive_size // 1024:5d} KB  (Lyria: 'bass line, 130 BPM, E minor, electric bass')")
    print(f"  engineered  {eng_size // 1024:5d} KB  (Lyria: 'solo electric bass guitar recording, dry')")
    return ({
        "base": "bass-engineering",
        "naive": {
            "file": "naive.mp3",
            "label": "Naive prompt → Demucs bass",
            "prompt": "bass line, 130 BPM, E minor, electric bass",
            "bass_db": -25.0,
            "drums_db": -16.3,
            "blurb": "Drums 8.7 dB louder than the bass itself — Lyria treated 'bass line' as a band track and Demucs couldn't undo it.",
        },
        "engineered": {
            "file": "engineered.mp3",
            "label": "Engineered prompt → Demucs bass",
            "prompt": "solo electric bass guitar recording, dry",
            "bass_db": -14.4,
            "drums_db": -48.9,
            "blurb": "Bass 34.5 dB louder than the drum residual — drums effectively silent.",
        },
        "swing_db": 43.2,
    }, naive_size + eng_size)


def main() -> int:
    DST_ROOT.mkdir(parents=True, exist_ok=True)

    mixer,   mixer_bytes    = build_mixer()
    a_combat, a_combat_bytes = build_adaptive_combat()
    isolated, isolated_bytes = build_stems_isolated()
    bass_ab, bass_ab_bytes   = build_bass_ab()
    bass_eng, bass_eng_bytes = build_bass_engineering()

    # Naive-prompt bass — kept around for potential reuse in use case
    # 03b but no longer referenced from the page.
    naive_bytes = 0
    naive_entry = None
    if NAIVE_BASS_SRC.is_file():
        naive_bytes = copy_mp3(NAIVE_BASS_SRC, NAIVE_BASS_DST)
        naive_entry = {
            "label": "Naive bass prompt",
            "prompt": "bass line, 130 BPM, E minor, electric bass",
            "blurb": "Lyria gave back bass *and* drums because the prompt didn't say not to.",
            "base": "naive",
            "file": "bass.mp3",
        }
        print(f"(retained) naive bass: {naive_bytes // 1024} KB")

    manifest = {
        "version": 6,
        "mixer": mixer,
        "adaptive_combat": a_combat,
        "stems_isolated": isolated,
        "bass_ab": bass_ab,
        "bass_engineering": bass_eng,
        "naive_bass": naive_entry,
    }
    (DST_ROOT / "manifest.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )
    total_mb = (mixer_bytes + a_combat_bytes + isolated_bytes
                + bass_ab_bytes + bass_eng_bytes + naive_bytes) / 1024 / 1024
    print(f"\nWrote {(DST_ROOT / 'manifest.json').relative_to(ROOT)}  "
          f"({total_mb:.1f} MB audio total)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
